### ISSUE TITLE
用您的这款软件很多年了, 非常感谢

### ISSUE THREAD

**Issue by windworst** [satrong/node-dict#9]
虽然用的nodejs 8 版本很老了 但是真的很好用
我把他封装到docker里了 以后还能一直用^_^

**Comment by windworst** [comment]
放进shell配置文件里

Linux/MacOS
```shell
dict () {
  docker run --rm -it --network host apiv1/node-dict "$@"
}
```
Windows
```powershell
function global:dict () {
  docker run --rm -it --network host apiv1/node-dict $($args -join ' ')
}
```

**Comment by satrong** [comment]
哈哈，居然还有人在用呢，我好多年没维护了。我有空再维护一下

**Comment by satrong** [comment]
@windworst 已经更新到了 3.0.0 了， 需要 nodejs 16+。欢迎继续使用

**Comment by windworst** [comment]
> @windworst 已经更新到了 3.0.0 了， 需要 nodejs 16+。欢迎继续使用

挺好 这样可以推荐英语不好的前端朋友装这个软件, 如果是老版本安装在node20下会报警告
我自己在docker环境还是可以先用着nodejs 8封装的老版本 体积比新版本小40M左右
